const fs = require("fs");
let code = "";

function e(s) { return s.replace(/\\"/g, '\\\\"'); }

code += /* ============================================================ + "\n";
code +=    APP - Application Orchestrator + "\n";
code +=    ============================================================ */ + "\n";
code += ar App = (function() { + "\n";
code +=   "use strict"; + "\n";
code +=   var pollTimer = null; + "\n";
code +=   var cryptoData = []; + "\n";
code +=   var currentUser = null; + "\n";
code +=   var $ = function(id) { return document.getElementById(id); }; + "\n";
code +=   var init = function() { + "\n";
code +=     AdminService.init(); + "\n";
code +=     var pc = authPage; + "\n";
code +=     if (pc) Particles.init(pc); + "\n";
code +=     renderCountries(); + "\n";
code +=     fetchTechStocks(); + "\n";
code +=     fetchCountryIndices(); + "\n";
code +=     var t = localStorage.getItem("cv_theme") || "dark"; + "\n";
code +=     applyTheme(t); + "\n";
code +=     var u = AuthService.getUser(); + "\n";
code +=     if (u) { currentUser = u; startLoad(); } + "\n";
code +=     else if (AdminService.isLoggedIn()) { startLoad(); } + "\n";
code +=     else { showAuth(); } + "\n";
code +=   }; + "\n";
code +=   var showAuth = function() { + "\n";
code +=     var pages = document.querySelectorAll(".page"); + "\n";
code +=     pages.forEach(function(p) { p.classList.remove("active"); }); + "\n";
code +=     var ap = authPage; + "\n";
code +=     if (ap) ap.classList.add("active"); + "\n";
code +=   }; + "\n";
code +=   var startLoad = function() { + "\n";
code +=     var pages = document.querySelectorAll(".page"); + "\n";
code +=     pages.forEach(function(p) { p.classList.remove("active"); }); + "\n";
code +=     var lp = loadingPage; + "\n";
code +=     if (lp) lp.classList.add("active"); + "\n";
code +=     var bar = loadingBarFill; + "\n";
code +=     var st = loadingStatus; + "\n";
code +=     var elapsed = 0; + "\n";
code +=     var iv = setInterval(function() { + "\n";
code +=       elapsed += 100; + "\n";
code +=       var pct = Math.min(elapsed / 5000 * 100, 100); + "\n";
code +=       if (bar) bar.style.width = pct + "%"; + "\n";
code +=       if (elapsed >= 5000) { + "\n";
code +=         clearInterval(iv); + "\n";
code +=         if (bar) bar.style.width = "100%"; + "\n";
code +=         setTimeout(function() { + "\n";
code +=           initDash(); + "\n";
code +=           if (lp) lp.classList.remove("active"); + "\n";
code +=           var d = dashboardPage; + "\n";
code +=           if (d) d.classList.add("active"); + "\n";
code +=           startPolling(); + "\n";
code +=         }, 300); + "\n";
code +=       } + "\n";
code +=     }, 100); + "\n";
code +=   }; + "\n";
code +=   var initDash = function() { + "\n";
code +=     if (!currentUser) { var u = AuthService.getUser(); if (u) currentUser = u; } + "\n";
code +=     if (!currentUser) return; + "\n";
code +=     var g = greetingText; + "\n";
code +=     if (g) g.textContent = "Hello, " + currentUser.email.split("@")[0]; + "\n";
code +=     var de = currentDate; + "\n";
code +=     if (de) de.textContent = new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }); + "\n";
code +=     WalletService.init(currentUser.userId); + "\n";
code +=     fetchData(); + "\n";
code +=     renderHome(); + "\n";
code +=     renderProfile(); + "\n";
code +=   }; + "\n";
code +=   var fetchData = function() { + "\n";
code +=     MarketService.fetchCoins(function(data) { + "\n";
code +=       cryptoData = data; + "\n";
code +=       renderHome(); + "\n";
code +=       renderMarket(); + "\n";
code +=     }); + "\n";
code +=   }; + "\n";
code +=   var openCoinDetail = function(coin) { + "\n";
code +=     CoinDetail.show(coin, { + "\n";
code +=       onBuy: function(c) { openTradeModal(c, "buy"); }, + "\n";
code +=       onSell: function(c) { openTradeModal(c, "sell"); } + "\n";
code +=     }); + "\n";
code +=   }; + "\n";
code +=   var openTradeModal = function(coin, mode) { + "\n";
code +=     TradeModal.open(coin, mode, { + "\n";
code +=       balance: WalletService.getBalance(), + "\n";
code +=       holdings: WalletService.getHoldings(), + "\n";
code +=       onExecute: function(r) { + "\n";
code +=         if (r.mode === "buy") { + "\n";
code +=           var nb = WalletService.getBalance() - r.amount - r.fee; + "\n";
code +=           WalletService.setBalance(nb); + "\n";
code +=           WalletService.addHolding(r.coin.id, r.coin.name, r.coin.symbol, r.coin.image, r.quantity, r.price); + "\n";
code +=           WalletService.addTransaction({ type: "Buy", coin: r.coin.symbol.toUpperCase(), amount: r.amount, price: r.price, qty: r.quantity, fee: r.fee, date: new Date().toISOString() }); + "\n";
code +=         } else { + "\n";
code +=           var nb = WalletService.getBalance() + r.amount - r.fee; + "\n";
code +=           WalletService.setBalance(nb); + "\n";
code +=           WalletService.removeHolding(r.coin.id, r.quantity); + "\n";
code +=           WalletService.addTransaction({ type: "Sell", coin: r.coin.symbol.toUpperCase(), amount: r.amount, price: r.price, qty: r.quantity, fee: r.fee, date: new Date().toISOString() }); + "\n";
code +=         } + "\n";
code +=         renderPortfolio(); + "\n";
code +=         setTimeout(function() { Modal.close(); }, 1500); + "\n";
code +=       } + "\n";
code +=     }); + "\n";
code +=   }; + "\n";
code +=   var renderPortfolio = function() { + "\n";
code +=     var b = portfolioBalanceVal; + "\n";
code +=     if (b) b.textContent = "$" + WalletService.getBalance().toLocaleString("en-US", { minimumFractionDigits: 2 }); + "\n";
code +=     var h = portfolioHoldings; + "\n";
code +=     if (h) { + "\n";
code +=       var hd = WalletService.getHoldings(); + "\n";
code +=       var keys = Object.keys(hd); + "\n";
code +=       if (!keys.length) { + "\n";
code +=         h.innerHTML = "<div class=\\"admin-empty\\" style=\\"text-align:center;padding:32px 16px;color:var(--text2);font-size:13px\\">No open positions. Start trading now!</div>"; + "\n";
code +=       } else { + "\n";
code +=         var html = ""; + "\n";
code +=         for (var i = 0; i < keys.length; i++) { + "\n";
code +=           var item = hd[keys[i]]; + "\n";
code +=           var coin = cryptoData.find(function(c) { return c.id === keys[i]; }); + "\n";
code +=           var curPrice = coin ? coin.current_price : item.avgPrice; + "\n";
code +=           var val = item.qty * curPrice; + "\n";
code +=           var pnl = ((curPrice - item.avgPrice) / item.avgPrice * 100); + "\n";
code +=           html += "<div class=\\"holding-item\\"><div class=\\"hi-left\\"><div class=\\"hi-name\\">" + item.symbol.toUpperCase() + "</div><div class=\\"hi-qty\\">" + item.qty.toFixed(6) + "</div></div><div class=\\"hi-right\\"><div class=\\"hi-value\\">$" + val.toFixed(2) + "</div><div class=\\"hi-pnl " + (pnl >= 0 ? "positive" : "negative") + "\\">" + (pnl >= 0 ? "+" : "") + pnl.toFixed(2) + "%</div></div></div>"; + "\n";
code +=         } + "\n";
code +=         h.innerHTML = html; + "\n";
code +=       } + "\n";
code +=     } + "\n";
code +=     var hist = portfolioHistory; + "\n";
code +=     if (hist) { + "\n";
code +=       var txns = WalletService.getTransactions(); + "\n";
code +=       if (!txns.length) { + "\n";
code +=         hist.innerHTML = "<div class=\\"admin-empty\\" style=\\"text-align:center;padding:32px 16px;color:var(--text2);font-size:13px\\">No transaction history yet.</div>"; + "\n";
code +=       } else { + "\n";
code +=         var html = ""; + "\n";
code +=         for (var i = txns.length - 1; i >= Math.max(0, txns.length - 20); i--) { + "\n";
code +=           var t = txns[i]; + "\n";
code +=           var cl = t.type === "Buy" ? "positive" : "negative"; + "\n";
code +=           html += "<div class=\\"txn-item\\"><div class=\\"txn-left\\"><span class=\\"txn-type " + cl + "\\">" + t.type + "</span> <span class=\\"txn-coin\\">" + t.coin + "</span></div><div class=\\"txn-right\\"><span class=\\"txn-amount\\">$" + t.amount.toFixed(2) + "</span><span class=\\"txn-date\\">" + new Date(t.date).toLocaleDateString() + "</span></div></div>"; + "\n";
code +=         } + "\n";
code +=         hist.innerHTML = html; + "\n";
code +=       } + "\n";
code +=     } + "\n";
code +=     var tv = WalletService.getPortfolioValue(cryptoData); + "\n";
code +=     var pst = psTotalVal; + "\n";
code +=     if (pst) pst.textContent = "$" + (WalletService.getBalance() + tv).toFixed(2); + "\n";
code +=     var pst2 = psTrades; + "\n";
code +=     if (pst2) pst2.textContent = Object.keys(WalletService.getHoldings()).length; + "\n";
code +=   }; + "\n";
code +=   var renderProfile = function() { + "\n";
code +=     if (!currentUser) return; + "\n";
code +=     profileName.textContent = currentUser.email.split("@")[0]; + "\n";
code +=     profileEmail.textContent = currentUser.email; + "\n";
code +=     profileAvatarLetter.textContent = currentUser.email.charAt(0).toUpperCase(); + "\n";
code +=     accEmail.textContent = currentUser.email; + "\n";
code +=     accUsername.textContent = currentUser.email.split("@")[0]; + "\n";
code +=     accMemberSince.textContent = currentUser.createdAt ? new Date(currentUser.createdAt).toLocaleDateString() : "Today"; + "\n";
code +=     accLastLogin.textContent = "Just now"; + "\n";
code +=     accId.textContent = currentUser.userId || "--"; + "\n";
code +=     accTimezone.textContent = Intl.DateTimeFormat().resolvedOptions().timeZone; + "\n";
code +=   }; + "\n";
code +=   var renderCountries = function() { + "\n";
code +=     var g = countryStocksGrid; + "\n";
code +=     if (!g) return; + "\n";
code +=     var countries = Config.countries; + "\n";
code +=     if (!countries) return; + "\n";
code +=     var h = ""; + "\n";
code +=     for (var i = 0; i < countries.length; i++) { + "\n";
code +=       var c = countries[i]; + "\n";
code +=       h += "<div class=\\"country-stock-card\\"><div class=\\"cs-flag\\">" + c.flag + "</div><div class=\\"cs-name\\">" + c.idx + "</div><div class=\\"cs-ex\\">" + c.ex + "</div><div class=\\"cs-price\\">$" + c.price.toLocaleString() + "</div><div class=\\"cs-change " + (c.chg >= 0 ? "positive" : "negative") + "\\">" + (c.chg >= 0 ? "+" : "") + c.chg.toFixed(2) + "%</div></div>"; + "\n";
code +=     } + "\n";
code +=     g.innerHTML = h; + "\n";
code +=   }; + "\n";
code +=   var fetchCountryIndices = function() { + "\n";
code +=     MarketService.fetchCountryIndices(Config.countries, function() { renderCountries(); }); + "\n";
code +=   }; + "\n";
code +=   var fetchTechStocks = function() { + "\n";
code +=     MarketService.fetchTechStocks(Config.techStocks, function(stocks) { + "\n";
code +=       var list = techStocksList; + "\n";
code +=       if (!list) return; + "\n";
code +=       var h = ""; + "\n";
code +=       for (var i = 0; i < stocks.length; i++) { + "\n";
code +=         var t = stocks[i]; + "\n";
code +=         var cls = t.chg >= 0 ? "positive" : "negative"; + "\n";
code +=         var arrow = t.chg >= 0 ? "&#9650;" : "&#9660;"; + "\n";
code +=         h += "<div class=\\"crypto-item\\"><div class=\\"crypto-left\\"><div><div class=\\"crypto-name\\">" + t.name + "</div><div class=\\"crypto-symbol\\">" + t.symbol + "</div></div></div><div class=\\"crypto-right\\"><div class=\\"crypto-price\\">$" + t.price.toLocaleString() + "</div><div class=\\"crypto-change " + cls + "\\">" + arrow + " " + Math.abs(t.chg).toFixed(2) + "%</div></div></div>"; + "\n";
code +=       } + "\n";
code +=       list.innerHTML = h; + "\n";
code +=     }); + "\n";
code +=   }; + "\n";
code +=   var marketSearchBound = false; + "\n";
code +=   var renderMarket = function() { + "\n";
code +=     if (!cryptoData || !cryptoData.length) return; + "\n";
code +=     var list = marketCryptoList; + "\n";
code +=     if (!list) return; + "\n";
code +=     var h = ""; + "\n";
code +=     for (var i = 0; i < cryptoData.length; i++) { + "\n";
code +=       var c = cryptoData[i]; + "\n";
code +=       var chg = c.price_change_percentage_24h || 0; + "\n";
code +=       var cls = chg >= 0 ? "positive" : "negative"; + "\n";
code +=       h += "<div class=\\"analytical-row\\" data-id=\\"" + c.id + "\\">"; + "\n";
code +=       h += "<div class=\\"ar-left\\"><img class=\\"ar-icon\\" src=\\"" + c.image + "\\" alt=\\"\\" onerror=\\"this.style.display=\\'none\\'\\">"; + "\n";
code +=       h += "<div class=\\"ar-info\\"><div class=\\"ar-name\\">" + c.name + "</div><div class=\\"ar-symbol\\">" + c.symbol.toUpperCase() + "</div></div></div>"; + "\n";
code +=       h += "<div class=\\"ar-price\\">$" + c.current_price.toLocaleString("en-US", { minimumFractionDigits: 2 }) + "</div>"; + "\n";
code +=       h += "<div class=\\"ar-change " + cls + "\\">" + chg.toFixed(2) + "%</div>"; + "\n";
code +=       h += "<div class=\\"ar-cap\\">$" + (c.market_cap / 1e9).toFixed(2) + "B</div></div>"; + "\n";
code +=     } + "\n";
code +=     list.innerHTML = h; + "\n";
code +=     list.querySelectorAll(".analytical-row").forEach(function(item) { + "\n";
code +=       item.addEventListener("click", function() { + "\n";
code +=         var id = this.dataset.id; + "\n";
code +=         var coin = cryptoData.find(function(c) { return c.id === id; }); + "\n";
code +=         if (coin) openCoinDetail(coin); + "\n";
code +=       }); + "\n";
code +=     }); + "\n";
code +=     var search = marketSearch; + "\n";
code +=     if (search && !marketSearchBound) { + "\n";
code +=       marketSearchBound = true; + "\n";
code +=       search.addEventListener("input", function() { + "\n";
code +=         var q = this.value.toLowerCase(); + "\n";
code +=         var rows = list.querySelectorAll(".analytical-row"); + "\n";
code +=         for (var i = 0; i < rows.length; i++) { + "\n";
code +=           rows[i].style.display = rows[i].textContent.toLowerCase().indexOf(q) > -1 ? "flex" : "none"; + "\n";
code +=         } + "\n";
code +=       }); + "\n";
code +=     } + "\n";
code +=     var summary = MarketService.getSummary(); + "\n";
code +=     if (summary) { + "\n";
code +=       var btcDom = btcDominance; + "\n";
code +=       if (btcDom) btcDom.textContent = summary.btcDominance.toFixed(1) + "%"; + "\n";
code +=       var vol = totalVolume; + "\n";
code +=       if (vol) vol.textContent = "$" + (summary.totalVolume / 1e9).toFixed(2) + "B"; + "\n";
code +=       var gainer = topGainers; + "\n";
code +=       if (gainer) gainer.textContent = summary.topGainer; + "\n";
code +=       var loser = topLosers; + "\n";
code +=       if (loser) loser.textContent = summary.topLoser; + "\n";
code +=       var count = coinCount; + "\n";
code +=       if (count) count.textContent = summary.count + " coins"; + "\n";
code +=     } + "\n";
code +=   }; + "\n";
code +=   var renderAdmin = function() { + "\n";
code +=     var stats = AdminService.getStats(); + "\n";
code +=     adminTotalUsers.textContent = stats.total; + "\n";
code +=     adminActiveUsers.textContent = stats.active; + "\n";
code +=     adminBlockedUsers.textContent = stats.blocked; + "\n";
code +=     adminOnlineUsers.textContent = stats.online; + "\n";
code +=   }; + "\n";
code +=   var applyTheme = function(theme) { + "\n";
code +=     document.documentElement.setAttribute("data-theme", theme); + "\n";
code +=     localStorage.setItem("cv_theme", theme); + "\n";
code +=     if (theme === "light") document.body.classList.add("light-theme"); + "\n";
code +=     else document.body.classList.remove("light-theme"); + "\n";
code +=   }; + "\n";
code +=   var startPolling = function() { + "\n";
code +=     if (pollTimer) clearInterval(pollTimer); + "\n";
code +=     pollTimer = setInterval(function() { + "\n";
code +=       fetchData(); + "\n";
code +=       fetchCountryIndices(); + "\n";
code +=       fetchTechStocks(); + "\n";
code +=     }, 30000); + "\n";
code +=   }; + "\n";
code +=   var wireEvents = function() { + "\n";
code +=     document.querySelectorAll(".nav-btn").forEach(function(btn) { + "\n";
code +=       btn.addEventListener("click", function() { + "\n";
code +=         var tab = this.dataset.tab; + "\n";
code +=         if (tab) { + "\n";
code +=           var contents = document.querySelectorAll(".tab-content"); + "\n";
code +=           contents.forEach(function(c) { c.classList.remove("active"); }); + "\n";
code +=           var target = ; + "\n";
code +=           if (target) target.classList.add("active"); + "\n";
code +=           var btns = document.querySelectorAll(".nav-btn"); + "\n";
code +=           btns.forEach(function(b) { b.classList.toggle("active", b.dataset.tab === tab); }); + "\n";
code +=           if (tab === "portfolioPage") { WalletService.init(currentUser ? currentUser.userId : ""); renderPortfolio(); } + "\n";
code +=           if (tab === "adminPage") renderAdmin(); + "\n";
code +=         } + "\n";
code +=       }); + "\n";
code +=     }); + "\n";
code +=     var forgotLink = forgotPwdLink; + "\n";
code +=     if (forgotLink) { + "\n";
code +=       forgotLink.addEventListener("click", function(e) { + "\n";
code +=         e.preventDefault(); + "\n";
code +=         Modal.alert({ title: "Password Reset", message: "Password reset is not available in demo mode. Please contact support at: support@live-market.app" }); + "\n";
code +=       }); + "\n";
code +=     } + "\n";
code +=     var logoutBtn = logoutBtn; + "\n";
code +=     if (logoutBtn) { + "\n";
code +=       logoutBtn.addEventListener("click", function() { + "\n";
code +=         AuthService.logout(); + "\n";
code +=         if (AdminService.isLoggedIn()) AdminService.logout(); + "\n";
code +=         if (pollTimer) { clearInterval(pollTimer); pollTimer = null; } + "\n";
code +=         currentUser = null; + "\n";
code +=         var pages = document.querySelectorAll(".page"); + "\n";
code +=         pages.forEach(function(p) { p.classList.remove("active"); }); + "\n";
code +=         var ap = authPage; + "\n";
code +=         if (ap) ap.classList.add("active"); + "\n";
code +=       }); + "\n";
code +=     } + "\n";
code +=   }; + "\n";
code +=   return { init: function() { + "\n";
code +=     document.addEventListener("DOMContentLoaded", function() { + "\n";
code +=       try { init(); } catch(e) { console.error("App.init:", e); } + "\n";
code +=       try { wireEvents(); } catch(e) { console.error("App.wireEvents:", e); } + "\n";
code +=     }); + "\n";
code +=   }}; + "\n";
code += })(); + "\n";
code += App.init(); + "\n";

fs.writeFileSync("src/app.js", code);
console.log("Generated app.js successfully");
